### PR TITLE
Fix ReservedValidator (Re-PR without formatting code)

### PR DESCRIPTION
**Pull request by geekfil**
Added the replaceReserved method to the ReservedValidator class.
This solves the problem with custom error messages.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@bennothommo @w20k could you test this?

**Comment by bennothommo** [comment]
@LukeTowers The validation all works fine after this fix. The only minor thing I noticed is that the attribute in the error message is presented in underscore format with this fix in place.

Before:
Before fix
After:
After fix

**Comment by geekfil** [comment]
> @LukeTowers @geekfil The validation all works fine after this fix. The only minor thing I noticed is that the attribute in the error message is presented in underscore format with this fix in place.
> 
> Before:
> Before fix
> After:
> After fix

Sorry, I didn't. It's easy to fix.
We need to replace this:
```
public function replaceReserved($message, $attribute, $rule, $parameters)
{
        return str_replace(':attribute', $attribute, e(trans('rainlab.builder::lang.validation.reserved')));
}
```
with this:
```
public function replaceReserved($message, $attribute, $rule, $parameters)
{
        return $this->replaceAttributePlaceholder(e(trans('rainlab.builder::lang.validation.reserved')), ucfirst($this->getDisplayableAttribute($attribute)));
}
```
Result:
image

I'm not strong at Git. How can I make changes to this PR? or need to create a new PR?

**Comment by LukeTowers** [comment]
@bennothommo could you test his latest changes?

**Comment by bennothommo** [comment]
@LukeTowers Yep, all looks good. Thanks for the edits @geekfil

**Pull request merged**
