### PR TITLE
Add reserved keyword check for namespaces

### PR DESCRIPTION
**Pull request by bennothommo**
Fixes issue #256.

I was not sure of where to put the validation messages, so it is currently in `Plugin.php` as part of the validator registration. Happy to take advice on where this may be better implemented.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Awesome, thanks very much @bennothommo! This looks great! Do you have any interest in also making a PR to the core to beef up the handling of invalid plugin files?

**Comment by bennothommo** [comment]
@LukeTowers Sure thing, I'll give it a try.

**Comment by geekfil** [comment]
Sorry, but this code creates problems.
```
Validator::resolver(function ($translator, $data, $rules, $messages, $customAttributes) {
            $messages = [
                'reserved' => e(trans('rainlab.builder::lang.validation.reserved'))
            ];
             return new ReservedValidator($translator, $data, $rules, $messages, $customAttributes);
        });
```
https://octobercms.com/docs/services/validation#custom-error-messages
Custom error messages no longer work.
The "array_merge" function for "$messages" solves the problem, but I'm not sure that this is correct.

**Comment by LukeTowers** [comment]
@geekfil feel free to submit an array_merge fix for the messages issue.

**Comment by bennothommo** [comment]
@LukeTowers Would it be worth maybe implementing the "reserved" validator into core October (possibly as a [custom rule object](https://laravel.com/docs/5.5/validation#custom-validation-rules)) and remove the resolver above? Would benefit both the entire October codebase and hopefully eliminate the issue @geekfil has pointed out above. Happy to do the work :)

**Comment by geekfil** [comment]
@bennothommo I solved the problem that I faced
https://github.com/rainlab/builder-plugin/pull/265

**Comment by bennothommo** [comment]
@geekfil I did see that, thanks heaps for that. I was simply suggesting moving this change out of the Builder plugin and making it available across October.

**Comment by LukeTowers** [comment]
@bennothommo it's worth discussing, right now I'm just not sure how many other use cases there are for validating values are not a reserved PHP word

**Comment by bennothommo** [comment]
That's a fair point.

**Comment by LukeTowers** [comment]
If you can think of any, I'd be more than willing to discuss it further. Thanks for your contributions on this, looking forwards to any future contributions from you!

**Pull request merged**
