### PR TITLE
Use class_exists in validateModelClassName for namespaced classes

### LINKED ISSUE #202: Handle lowercase namespaces
Note: This was mentioned in #162, but creating a separate ticket as these are not related.

### Steps to reproduce
1. Create a new plugin with a "plugin namespace" of all lower case (e.g. `rainlab` instead of `Rainlab`)
2. Go to CMS > Pages > [any page]
3. Navigate to Components
4. Drag new Builder > "Record List" onto the page.
5. Click the new component to show options.

Results: This causes a popup error
> Invalid model class name

### Workaround

Rename plugin namespace with first letter Uppercase  (e.g. `Rainlab` instead of `rainlab`)

### Handle lowercase namespaces
Request is to handle lowercase namespaces, since Larvel/October handles lowercase namespacing.

### PR DESCRIPTION
**Pull request by tleish**
Fixes #202 #150 #162

### CODE REVIEW

**Comment by LukeTowers** [comment]
Does this work when the builder plugin is creating a model class file?

**Comment by tleish** [comment]
Looks like it.  When creating a new model class, the code checks the name of the class itself (not the namespace) using the same method name in a different Class:

### builder/classes/ModelYamlModel.php
```php
    protected static function validateModelClassName($modelClassName)
    {
        // e.g. $modelClassName = "MyClass"
        return preg_match('/^[A-Z]+[a-zA-Z0-9_]+$/i', $modelClassName);
    }
```

Whereas this change affects
### builder/classes/ModelModel.php
```php
    public static function validateModelClassName($modelClassName, $allowNamespaces = false)
    {
       // e.g. $modelClassName = "MyClass"
        if (!$allowNamespaces) {
            return preg_match('/^[A-Z]+[a-zA-Z0-9_]+$/', $modelClassName);
        }

        // e.g. $modelClassName = "MyNamespace\Model\MyClass"
        return class_exists($modelClassName);
    }
```

**Comment by LukeTowers** [comment]
@tleish perfect thanks! Would you mind adding some tests for this to ensure that it stays fixed in the future?

**Comment by tleish** [comment]
I considered this initially, but there's no specific documentation about getting phpunit running.  Phpunit is not part of the composer.json` file.  When I tried to get the tests up and running, I gave up after a few minutes since getting phpunit to run was going to take me longer than writing the code or the tests.

Do you any or can you make some docs for getting phpunit running with this project?

**Comment by LukeTowers** [comment]
@tleish have you read http://octobercms.com/docs/help/unit-testing?

**Comment by tleish** [comment]
> ### Unit tests
>
> Unit tests can be performed by running phpunit in the root directory or inside /tests/unit.

I must be doing something wrong.

```
$ cd plugins/rainlab/builder/tests
$ ../vendor/bin/phpunit                                                                                                                                                                                             Tue Dec  5 09:08:02 2017
PHPUnit 7.0-g150bb8236 by Sebastian Bergmann and contributors.

Usage: phpunit [options] UnitTest [UnitTest.php]
       phpunit [options] <directory>

Code Coverage Options:

  --coverage-clover <file>    Generate code coverage report in Clover XML format.
  --coverage-crap4j <file>    Generate code coverage report in Crap4J XML format.
  --coverage-html <dir>       Generate code coverage report in HTML format.
...
```


```
$ cd plugins/rainlab/builder/tests/unit
$ ../vendor/bin/phpunit
> PHP Warning:  is_dir() expects parameter 1 to be a valid path, object given in /Users/tleishman/Sites/dev/october/web/plugins/rainlab/builder/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php on line 56
```

**Comment by LukeTowers** [comment]
I think that is written with a global install of phpunit in mind. Are you able to test that?

**Comment by tleish** [comment]
Note: Global version did not find any tests.  

```
$ cd tests/unit/
$ phpunit
PHPUnit 6.5.2 by Sebastian Bergmann and contributors.



Time: 86 ms, Memory: 10.00MB

No tests executed!
```

To get this working I added the following to the plugin composer.json, similar to what's in october.

```json
    "require-dev": {
      "phpunit/phpunit": "~4.0"
    }
```

The following command then worked.
```
$ cd tests/unit/
$ ../../vendor/bin/phpunit
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

.....

Time: 267 ms, Memory: 12.00MB

OK (5 tests, 21 assertions)
```

This is because my global phpunit is 6.5.2, while the local to the project 4.8.36.  So, the tests do not support phpunit 6.  Better documentation on unit testing and/or adding the supported version to composer.json would be helpful in the future.

**Comment by LukeTowers** [comment]
Thanks @tleish! If you could make adjustments to the docs repository and make a PR that would be appreciated!

**Comment by tleish** [comment]
@LukeTowers - unit test added

**Comment by LukeTowers** [comment]
Perfect, thanks @tleish! One last thing, could you change UNQUALIFIED_CLASS_NAME to CLASS_NAME_PATTERN?

**Comment by tleish** [comment]
I don't mind adding `_PATTERN` to the end, but I suggest keeping the `UNQUALIFIED_` prefix.  The reasoning behind this is because `CLASS_NAME_PATTERN` could communicate any of the following:

* MyClassName
* RainLab\Builder\Models\Settings
* \RainLab\Builder\Models\Settings

However, only the first is valid, which is Unqualified (see: http://php.net/manual/en/language.namespaces.basics.php).

However, I'm still happy to use your constant name if you want.

**Comment by tleish** [comment]
I renamed according to your direction.

**Comment by LukeTowers** [comment]
Good point @tleish, your recommendation makes sense. I misunderstood the regex at first glance, thought it was talking about unqualified and qualified class names.

**Comment by tleish** [comment]
Updated to `UNQUALIFIED_CLASS_NAME_PATTERN`.

**Comment by LukeTowers** [comment]
Bit wordy but it works 😂  Thanks for all your work on this!

**Pull request merged**
