### PR TITLE
Convert reserved validator to a rule object

### LINKED ISSUE #267: validator resolver code breaks other validator resolvers
Hello

It seems that the following code found in Plugin.php

 ```
 // Register reserved keyword validation

Validator::resolver(function ($translator, $data, $rules, $messages, $customAttributes) {
            return new ReservedValidator($translator, $data, $rules, $messages, $customAttributes);
 });
```

breaks all attempts to implement our own validators in a new plugin.

**What did I expect**
When I build a new plugin, I needed new validations. I implemented them using a class. That a new validation rule would work as expected

**What did I get**
My validation rules were not found (Method validateXyz not found). Even very simple validations taken out of the documentation.
After 4 hours of digging I discovered that if I comment out the above code in the Builder plugin then new validations work ok.

No idea why that is, just reporting it.

### PR DESCRIPTION
**Pull request by bennothommo**
Fixes #267.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@w20k could you test this please?

**Comment by w20k** [comment]
@LukeTowers, will do (in Testing Todo List)! But no sooner then 5th of Jan.

**Comment by w20k** [comment]
@bennothommo thanks for pinging :) Totally lost this ticket in a pile of ToDos.

**Comment by bennothommo** [comment]
@w20k haha, not a problem.

**Comment by w20k** [comment]
@bennothommo thanks a lot of pinging and dealing with this issue! Works, as expected, took me a while to get back. Crazy year)

@LukeTowers  - testing is done. Ready to be merged.

**Comment by LukeTowers** [comment]
Thanks guys!

**Comment by ayumi-cloud** [comment]
@bennothommo I see an error with this code.

Code lines: https://github.com/rainlab/builder-plugin/blob/8e9d93d2fe5c0a2a564b4be297f076d0eda33573/Plugin.php#L134-L139

Calls for the Rainlab.Translator plugin, but gives an error with new builds trying to install these plugins.

I think it needs a wrapper to only work when the Rainlab.Translator plugin - has been installed. If not installed it shouldn't run as gives an error.

See my comment here: https://github.com/octobercms/october/issues/4783#issuecomment-577721763

Sorrry I should of shared the builder plugin stack trace instead of my plugin. But both plugins do exact same thing as I used the exact same code.

~I wait for your reply with `bated breath`

**Comment by bennothommo** [comment]
@ayumi-cloud I think the issue might lie somewhere else, not from the Translate plugin. That event is for the core translator that translates system strings, and is available whether or not the Translate plugin is installed.

**Comment by ayumi-cloud** [comment]
@bennothommo going to look deeper into this, sorry I wrong with Rainlab.Translate it's coming from RainLab.User plugin instead, here's a screenshot anyway from a fresh install:

image

**Comment by ayumi-cloud** [comment]
Found the issue, it was a third party plugin, we removed their plugin and no problems.

**Pull request merged**
