### PR TITLE
Redo of #304

### PR DESCRIPTION
**Pull request by LukeTowers**
This is a resubmission of #304. @bennothommo please review and let me know what's left before it can be merged.

### CODE REVIEW

**Comment by bennothommo** [comment]
@LukeTowers it just needs to be tested, that's all. I believe @filipac sorted out the last issue that @w20k spotted.

**Comment by LukeTowers** [comment]
@w20k when you get a moment could you test this out?

**Comment by w20k** [comment]
@LukeTowers sure!

**Comment by LukeTowers** [comment]
@petehalverson eagerly awaiting octodock updates :)

**Comment by petehalverson** [comment]
Ok. [octodock](https://labs.octodock.com/) is back and ready to go!

**Comment by LukeTowers** [comment]
Thanks @petehalverson, appreciate it!

**Comment by w20k** [comment]
@LukeTowers seems like it's working properly now.
@petehalverson thanks a lot! ;)

Screenshots:
Screenshot 2019-11-05 at 21 38 05
Screenshot 2019-11-05 at 21 38 11

**Comment by LukeTowers** [comment]
Thanks @w20k. Good work on the feature @filipac!

**Pull request merged**
