### PR TITLE
Allow editing of migration file in "Confirm migration" popup in database table editor.

### PR DESCRIPTION
**Pull request by Air-Petr**
It's about our conversation in [i279](https://github.com/rainlab/builder-plugin/issues/279).

The main things:
1. I've [added](https://github.com/rainlab/builder-plugin/compare/master...Air-Petr:i279?expand=1#diff-f70fd9a557dd4fe957fa0a78b4dee002R137) the `Throwable` to handle errors in a migration code.
2. I've edited JS-scripts. Now after applying the migration a database table view (a backend page) is also updates.

### CODE REVIEW

**Comment by bennothommo** [comment]
@Air-Petr Excellent work! This works really well - well done!

Just a couple of minor issues I found during testing, hopefully they shouldn't take too long to sort out:

- When the migration table designer is refreshed, after saving the migration, the "Add timestamps" and "Add soft deleting support" buttons both disappear.
- If the "up" method is not available in the edited migration file, either because it is deleted or renamed, the AJAX request to save the migration fails but no error is passed back to the front-end.
- You will need to remove the note just above the code editor with the message "The migration code is read-only..."

**Comment by bennothommo** [comment]
On the second point above, I wonder if it might be better to show 2 code editors, one for the "up" migration and one for the "down" migration, and only showing the code for the actual field/table changes to prevent people from being silly and messing about with the migration methods. Any thoughts on that?

**Comment by LukeTowers** [comment]
@bennothommo As long as we have proper error handling in place to handle people being silly I'd rather it was just one code editor to empower the developer to do whatever they need / want to do. Sometimes you might want to add other methods. As long as we can gracefully handle people being silly there's no need to restrict the flexibility of the tool.

**Comment by Air-Petr** [comment]
@bennothommo I'll try to solve these issues as soon as possible. Thanks for your review.
> On the second point above, I wonder...

This is an interesting thought. But I agree with @LukeTowers: there could be some additional methods in the migration file. Though I can't imagine any situation where other methods are really needed 😅  It would be interesting to hear other opinions.

**Comment by LukeTowers** [comment]
Other methods would be purely for organizational purposes and mostly useful to do DB seeding, migrations by themselves are usually short enough to not need any other methods.

**Comment by bennothommo** [comment]
@Air-Petr @LukeTowers My justification for the suggestion was simply that if they want to do some sort of complex migration, they can use the *Versions* area. I feel this popup migration editor (or editors) is more for adding adjustments to the migration that cannot be done through the database table editor, for example, to add indexes or comments.

**Comment by Air-Petr** [comment]
> If the "up" method is not available in the edited...
@bennothommo It's strange, but I can't reproduce this issue. I always got `Call to undefined method...` in the error popup. I've tested with different php versions, but effect is the same. I have no idea how can it be...

**Comment by bennothommo** [comment]
@Air-Petr Not sure what was happening for me before, but I am getting the same error as you now as well, so that's fine.

I've tested your latest changes and everything is working as it should, so it's all good to merge. Thanks heaps for your contribution! :)

**Pull request merged**
